name: Production deployement
run-name: production deployement
on: 
  push:
    branches:
      - main

jobs:
  prod-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - name: Copy directory to Production via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }} # Defaults to 22 if not set
          source: "./dist/*"               # Local files/folders to copy
          target: "/var/www/app/"            # Remote target directory
          strip_components: 1                   # Prevents creating a "dist" folder inside target
          overwrite: true
          script: |
            sudo nginx -s reload
